alias WebKitCode="cd && qCodes && cd Apple/WebKit"
alias SwiftCode="cd && qCodes && cd Apple/Swift"
alias V8Code="cd && qCodes && cd V8"
alias UnrealCode="cd && qCodes && cd Unreal"
alias FlutterCode="cd && qCodes && cd Flutter/flutter/engine"
alias FireFoxCode="cd && qCodes && cd FireFox/FireFox"
alias ZenCode="cd && qCodes && cd Zen/desktop"
alias ZedCode="cd && qCodes && cd Zed/zed"
alias ElectronCode="cd && qCodes && cd Electron"
alias SkiaCode="cd && qCodes && cd Skia"
alias LinuxCode="cd && qCodes && cd Linux/linux"

alias FastClient="gclient sync --with_branch_heads --with_tags --no-history -v"